### PR TITLE
[!!] Refactor

### LINKED ISSUE #11: Refactor code
The current code is not dry, make functions

### PR DESCRIPTION
**Pull request by lnarita**
## What's been done?
+ Chopped the code down to functions
+ Organized files in folders :stuck_out_tongue: 
+ Replaced all calls to `Array.prototype.slice.call` to `Array.from` for readability
+ Add browser action (show popup)
+ Bump firebase to `v4.5.0`
+ _A lot of callback hell_

## Related Issues
Closes #11

## Tested on
Ubuntu 15.10 - Chrome 60
Windows 10   - Chrome 62

@jovit, @carlosamds please review
There a lot of changes in the PR and since I started working on this some time ago there might be some kind of code regression

### CODE REVIEW

**Review by carlosamds — COMMENTED** [review]
The code is readable, a miracle for what it was. Thank you for that.
I've tested the answer collection and the core seems to be working, but the dissertativas are not getting collected here. The problem is that the verification in line 29 from collector should take place in the test page, not in the grades page. Putting this verification after creating the fragment on line 41 should fix it.

**Comment by lnarita** [comment]
Thanks @carlosamds!
Just applied the fix, should be working now

**Comment by jovit** [comment]
The code is waay more reasonable now, this should make future changes a lot easier.
I'll run some tests to be on the safe side but everything looks fine

**Comment by carlosamds** [comment]
Awesome, collection working perfectly!
Just bump the version for the upload (> 1.2.1) and note that the name on the manifest is the name that goes on the store.

**Comment by jovit** [comment]
fixes https://github.com/jovit/fy-moodle/issues/11

**Pull request merged**
